# Generated by Django 5.2 on 2025-11-20 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('clinic_id', models.CharField(max_length=64)),
                ('clinic_name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('num_patients', models.IntegerField(default=0)),
                ('num_female', models.IntegerField(default=0)),
                ('num_male', models.IntegerField(default=0)),
                ('avg_age', models.FloatField(null=True)),
                ('top_symptoms', models.TextField(blank=True)),
                ('stock_shortage', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_risk', models.FloatField(null=True)),
            ],
        ),
    ]
